module.exports = {
  LOCALITY_NOT_FOUND: 'LOCALITY_NOT_FOUND',
  INCIDENT_NOT_EXIST_OR_ALREADY_ARCHIVE: 'INCIDENT_NOT_EXIST_OR_ALREADY_ARCHIVE',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
};
